 ---
 
 - name: Build windows Server
   hosts: Localhost
   serial: 1
   gather_facts: true
   connection: local
   tasks:
   - name: Deploy Web Servers
     clc_server:
       cpu: 1
       memory: 1
       description: 'Centos Server built via Runner'
       location: GB3
       group: 'Automation'
       managed_os: false
       name: WEB
       network_id: '7292dce1e6794b7682937824d2ce60d2'
       type: standard
       template: CentOS-6-64-TEMPLATE
       add_public_ip: false
       count: 10
       wait: yes
     register: clc
