 ---
 
 - name: Build windows Server
   hosts: Localhost
   serial: 1
   gather_facts: true
   connection: local
   tasks:
   - name: Deploy Web Servers
     clc_server:
       cpu: 1
       memory: 4
       description: 'Runner power up and down test'
       location: GB3
       group: 'Test power on group'
       managed_os: false
       name: MSTEST
       network_id: 'vlan_2040_10.105.40'
       type: standard
       template: WIN2012R2DTC-64
       add_public_ip: false
       count: 10
       wait: yes
     register: clc
