---
- name: Create infrastructure
  hosts: all
  gather_facts: False
  connection: local
  roles:
    - role: winsvr
      tags: 
        - infra

- name: Install software
  hosts: ctx_inv:ukgrp
  connection: winrm
  gather_facts: False
  roles:
    - role: python
      tags: 
        - config
    - role: iis 
      tags: 
        - iis
