---
- name: Create Networks
  hosts: all
  gather_facts: False
  tasks:
     - name: Create Networks
       clc_network:
         location: 'GB3'
         state: present
         name: 'Demo Runner VLAN'
         description: 'Demo Runner VLAN'
       register: net
